### ISSUE TITLE
Closure recommendation for nested DSLs?

### ISSUE THREAD

**Issue by mkobit** [gradle-guides/implementing-gradle-plugins#12] opened 2017-09-26 14:24 UTC
> If you need second- or third-level nesting, you will also have to add overloads that take a `Closure`, because Gradle cannot instrument nested extensions at the moment.

Shouldn't the method overloads take an `Action` instead to work better with the Kotlin DSL?

**Comment by bmuschko** [comment] 2017-09-26 14:30
This comment is not obsolete with the release of 4.2. We introduced a public API for nested DSLs. This sentence is out-of-date and would need refer to `ObjectFactory`. I am going to fix that soon.

**Comment by eriwen** [comment] 2018-02-13 21:03
Is this basically a duplicate of #9 then @bmuschko?

**Comment by mkobit** [comment] 2018-02-13 22:01
My understanding is that the `ObjectFactory` things just create those types, but you still need API methods to open up the API for use for both Kotlin and Groovy build scripts

The example at https://docs.gradle.org/current/userguide/custom_plugins.html#sec:nested_dsl_elementshas even has `void greeter(Action<? super Person> action)` so that the nested DSL can be used. There are a bunch of plugins out there now that use `Closure<>` type methods that make them extremely unwieldy to use with the Kotlin DSL.

**Comment by bmuschko** [comment] 2018-02-13 22:07
@eriwen I think so, yes.
@mkobit I am not quite sure I understood your last comment. Can you please point me to concrete examples in this guide and what you think need to change?

**Comment by mkobit** [comment] 2018-02-13 22:18
Sorry @bmuschko , I wasn't clear.

I think that the user guide at https://docs.gradle.org/current/userguide/custom_plugins.html#sec:nested_dsl_elements is more correct in that it suggests adding methods like `greeter(Action<? super Person> action)` that work well with both Groovy and Kotlin build script. For top level extensions, that decoration just seems to work, but for any nested extensions the `Action<>` methods are needed (in my experience). Maybe this will change when https://github.com/gradle/kotlin-dsl/issues/457 is implemented.

I originally just wanted to  suggest changing the wording on the guides page at https://guides.gradle.org/implementing-gradle-plugins/ from 

> If you need second- or third-level nesting, you will also have to add overloads that take a **`Closure`**, because Gradle cannot instrument nested extensions at the moment.

To suggest using `Action` instead of `Closure`. I don't remember if the user guide (compared to the Gradle Guides?) had that nested example before I wrote this issue.

**Comment by lacasseio** [comment] 2019-12-23 15:58
Issue moved to [gradle/guides #223](https://github.com/gradle/guides/issues/223) via [**ZenHub**](https://www.zenhub.com/)

**Closed by lacasseio** 2019-12-23 15:58 UTC
